[project]
name = "pde-find"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "ipykernel>=6.29.5",
    "matplotlib>=3.10.0",
    "numpy>=2.2.1",
    "scikit-learn>=1.6.1",
    "torch>=2.5.1",
    "tqdm>=4.67.1",
]
